name : node.js CI
on:
  push:
    branches:
       - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v2
      - name: configurar node
        uses: actions/setup-node@v2
        with:
           node-version: 24
      - name: ejecutar arhivo
        run: node index.js   
                